language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 4
script: npm run lint && npm run flow_check && npm run test:travis
deploy:
  skip_cleanup: true
  provider: npm
  email: shaun.stanworth@googlemail.com
  api_key:
    secure: GZYjtI8/5i4Rxu/lfFLpXG53y1VtzzvX3FMkrNIkuwAJCkRKUi0qTaOXVfRosfCTmjmqRcztGXeFUTkloi/AUZIzW6Wo32IZ8e8jcJ1LHEmvN+xFkBKX9FlNAJ/B6t1svGE878v2FfQegmawIQG1BHuUOFXnIxQkswDrzwpAtynkLJ3FkiftzZaFYplD2ZrOFfZGDhkiFnFXo9Rw5CcoufyyXcZbo91lL6HMUOjc2W74i3kv/2uOqu2CnsptwnoA53XfPpaS2NUh4aXllqCplvtJsNaH9LzPA8UICIEY4ZLXR1akV0tz4y6ec3hz2A3M1Tuau2XabfaP1TSOnjCckuaP+YRk1PFasmhuxEZyI3ULSyOkkdmPmnn2pE3pOAbhiB3Jt/hkiD1x/Xj/lKb8BgIPBlGQGgGFORGKyE2UG5oU7qxyjT4QUmGUvMbftZs13KDIurMmLArUqi7RMEFTnKTvHs2u2u1x435S91dZpxKU510Pabn379/E+s4Dc7ss2ks2x3GWtZrKI6eV/loEyI/f3N1TOmeHOpFlVk7I0BrapGIlzBOGzEPFd4ULpXx406vbFz9Q9dGjvSzM6wzAPxdb6+ku9R60hR5nKFsFCtR89K+QQafi3M1hmmcYIThlQZEOlCkcV2ifD3ZiE2ov82EYLa1mS3kOcBpgW9X5X54=
  on:
    repo: shauns/react-d3-axis
    branch: master
